////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace WebApiCore.Models
//{
//    using System;
//    using System.Data.Entity;
//    using System.Data.Entity.Infrastructure;
//    using System.Linq;
//    using System.Linq.Expressions;
//    using System.Threading.Tasks;

//    public partial class WebApiDataEntities : DbContext
//    {
//        public WebApiDataEntities()
//            : base("name=WebApiDataEntities")
//        {
//        }

//        protected override void OnModelCreating(DbModelBuilder modelBuilder)
//        {

//            //foreach (var entityType in modelBuilder.Model.GetEntityTypes())
//            //{
//            //    var isActiveProperty = entityType.FindProperty("IsActive");
//            //    if (isActiveProperty != null && isActiveProperty.ClrType == typeof(bool))
//            //    {
//            //        var parameter = Expression.Parameter(entityType.ClrType, "p");
//            //        var filter = Expression.Lambda(Expression.Property(parameter, isActiveProperty.PropertyInfo), parameter);
//            //        entityType.QueryFilter = filter;
//            //    }
//            //}

//            throw new UnintentionalCodeFirstException();
//        }
//        public override async Task<int> SaveChangesAsync()
//        {
//            AddBaseInfomation();
//            return await base.SaveChangesAsync();
//        }

//        public override int SaveChanges()
//        {
//            AddBaseInfomation();
//            return base.SaveChanges();
//        }
//        public void AddBaseInfomation()
//        {
//            var entities = ChangeTracker.Entries().Where(x => (x.State == EntityState.Added || x.State == EntityState.Modified));

//            var currentUsername = !string.IsNullOrEmpty(System.Web.HttpContext.Current?.User?.Identity?.Name)
//                ? System.Web.HttpContext.Current.User.Identity.Name
//                : "Anonymous";

//            foreach (var entity in entities)
//            {
//                if (entity.State == EntityState.Added)
//                {
//                    entity.Property("FCreateTime").CurrentValue = DateTime.Now;
//                    entity.Property("FUserCreate").CurrentValue = currentUsername;
//                }
//                entity.Property("FUpdateTime").CurrentValue = DateTime.Now;
//                //((BaseEntity)entity.Entity).FUpdateTime = DateTime.Now;
//                //((BaseEntity)entity.Entity).UserModified = currentUsername;
//            }
//        }
//        public virtual DbSet<MainMenu> MainMenus { get; set; }
//        public virtual DbSet<Menu> Menus { get; set; }
//        public virtual DbSet<Permission> Permissions { get; set; }
//        public virtual DbSet<Company> Companies { get; set; }
//        public virtual DbSet<Organization> Organizations { get; set; }
//        public virtual DbSet<AutoID> AutoIDs { get; set; }
//        public virtual DbSet<UserProfile> UserProfiles { get; set; }
//    }
//}
