//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_MA_CK
    {
        public int Id { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FDescription { get; set; }
        public Nullable<bool> FInUse { get; set; }
        public string FUserCreate { get; set; }
        public string FUserEdit { get; set; }
        public string FUserUpdate { get; set; }
        public string FUserDelete { get; set; }
        public Nullable<bool> FIsDelete { get; set; }
        public Nullable<bool> FIsEdit { get; set; }
        public Nullable<bool> FIsUpdate { get; set; }
        public Nullable<System.DateTime> FViewTime { get; set; }
        public Nullable<System.DateTime> FEditTime { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
        public Nullable<System.DateTime> FUpdateTime { get; set; }
        public Nullable<System.DateTime> FDeleteTime { get; set; }
        public string FLanguage { get; set; }
        public Nullable<int> FIndex { get; set; }
        public Nullable<int> FLevel { get; set; }
        public Nullable<bool> IsUnit { get; set; }
        public string FBranchCode { get; set; }
        public Nullable<double> GiaTran { get; set; }
        public Nullable<double> GiaSan { get; set; }
        public Nullable<double> GiaThamChieu { get; set; }
        public string FNote { get; set; }
        public string MaChungKhoan { get; set; }
    }
}
