//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    public partial class Donvi_Role
    {
        public string FullName { get; set; }
        public string Department { get; set; }
    }
    public partial class Donvi_Role_Model
    {
        public long Id { get; set; }
        public Nullable<long> FCodeDv { get; set; }
        public string UserName { get; set; }
        public string FDescription { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
        public Nullable<System.DateTime> FUpdateTime { get; set; }
        public string FUserCreate { get; set; }
        public string FUserApprove { get; set; }
        public Nullable<System.DateTime> FApproveTime { get; set; }
        public string FBranchCode { get; set; }
        public string FUserUpdate { get; set; }
        public string SearchKey { get; set; }
        public string FullName { get; set; }
        public string Department { get; set; }
    }
    public partial class DonviModel
    {
        public long Id { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FType { get; set; }
        public string UserName { get; set; }
    }
    public class DonViRoleFilterModel : FilterModel
    {
        public long? FcodeDv { get; set; }
        public string Department { get; set; }
    }
}
